/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FamilyRaya {
  'familyName' : string,
  'members' : Array<string>,
  'createdAt' : Time,
  'platter' : string,
}
export interface SummaryStats {
  'totalFamilies' : bigint,
  'totalFoodTypes' : bigint,
  'totalAttendees' : bigint,
  'largestFamilyName' : string,
  'largestFamilySize' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFamily' : ActorMethod<[FamilyRaya], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFamily' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFamilies' : ActorMethod<[], Array<FamilyRaya>>,
  'getFamily' : ActorMethod<[string], FamilyRaya>,
  'getFamilyCount' : ActorMethod<[], bigint>,
  'getFoodBreakdown' : ActorMethod<[], Array<[string, bigint]>>,
  'getLargestFamily' : ActorMethod<
    [],
    [] | [{ 'name' : string, 'size' : bigint }]
  >,
  'getMemberCount' : ActorMethod<[], bigint>,
  'getSummaryStats' : ActorMethod<[], SummaryStats>,
  'getUniqueFoodTypesCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetFamilies' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFamily' : ActorMethod<[string, FamilyRaya], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];