/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const FamilyRaya = IDL.Record({
  'familyName' : IDL.Text,
  'members' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'platter' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SummaryStats = IDL.Record({
  'totalFamilies' : IDL.Nat,
  'totalFoodTypes' : IDL.Nat,
  'totalAttendees' : IDL.Nat,
  'largestFamilyName' : IDL.Text,
  'largestFamilySize' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFamily' : IDL.Func([FamilyRaya], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFamily' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFamilies' : IDL.Func([], [IDL.Vec(FamilyRaya)], ['query']),
  'getFamily' : IDL.Func([IDL.Text], [FamilyRaya], ['query']),
  'getFamilyCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getFoodBreakdown' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getLargestFamily' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'size' : IDL.Nat }))],
      ['query'],
    ),
  'getMemberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSummaryStats' : IDL.Func([], [SummaryStats], ['query']),
  'getUniqueFoodTypesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetFamilies' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFamily' : IDL.Func([IDL.Text, FamilyRaya], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const FamilyRaya = IDL.Record({
    'familyName' : IDL.Text,
    'members' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'platter' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SummaryStats = IDL.Record({
    'totalFamilies' : IDL.Nat,
    'totalFoodTypes' : IDL.Nat,
    'totalAttendees' : IDL.Nat,
    'largestFamilyName' : IDL.Text,
    'largestFamilySize' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFamily' : IDL.Func([FamilyRaya], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFamily' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFamilies' : IDL.Func([], [IDL.Vec(FamilyRaya)], ['query']),
    'getFamily' : IDL.Func([IDL.Text], [FamilyRaya], ['query']),
    'getFamilyCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getFoodBreakdown' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getLargestFamily' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'size' : IDL.Nat }))],
        ['query'],
      ),
    'getMemberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSummaryStats' : IDL.Func([], [SummaryStats], ['query']),
    'getUniqueFoodTypesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetFamilies' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFamily' : IDL.Func([IDL.Text, FamilyRaya], [], []),
  });
};

export const init = ({ IDL }) => { return []; };